### ISSUE TITLE
Model doesn't predict

### ISSUE THREAD

**Issue by adelmuursepp** [kb22/ML-React-App-Template#12]
Everything works with the iris model but when I tried to generate my own model from data, it didn't return the prediction.

I will be very happy to find an answer to this problem.

https://github.com/adelmuursepp/ML-React-App-Template

**Comment by kb22** [comment]
Hey,
What all did you update? 
You can refer my article on this which describes all the things that need to be updated for your new model to start accepting information and make predictions.
Here's the link: https://towardsdatascience.com/create-a-complete-machine-learning-web-application-using-react-and-flask-859340bddb33
Thanks!

**Comment by adelmuursepp** [comment]
Thank you for help! I figured out that the model didn't save correctly.
Your template rocks!
